<?php
namespace App\Http\Controllers;
use App\Models\{User,Product,Category,Cart,CartItem,Order,OrderItem,Address,Wishlist,ApiToken,Review};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Hash,DB,Password};
use Illuminate\Support\Str;

class ApiController extends Controller {
 private function token(User $u){$raw='ameora_'.Str::random(64);ApiToken::create(['user_id'=>$u->id,'token_hash'=>hash('sha256',$raw),'expires_at'=>now()->addDays(30)]);return $raw;}
 private function user(User $u){return ['id'=>(string)$u->id,'email'=>$u->email,'firstName'=>$u->first_name ?: Str::before($u->name,' '),'lastName'=>$u->last_name ?: Str::after($u->name,' '),'phone'=>$u->phone,'addresses'=>$u->addresses->map(fn($a)=>['id'=>(string)$a->id,'label'=>$a->label,'firstName'=>$a->first_name,'lastName'=>$a->last_name,'line1'=>$a->line1,'line2'=>$a->line2,'city'=>$a->city,'state'=>$a->state,'postalCode'=>$a->postal_code,'country'=>$a->country,'isDefault'=>$a->is_default])];}
 private function cart(Request $r){$u=$r->user(); return Cart::firstOrCreate($u?['user_id'=>$u->id]:['guest_token'=>$r->header('x-guest-token') ?: $r->input('guestToken')]);}
 public function health(){return ['status'=>'ok','service'=>'ameora-laravel'];}
 public function register(Request $r){$d=$r->validate(['email'=>'required|email|unique:users','password'=>'required|min:8','firstName'=>'required|string','lastName'=>'required|string']);$u=User::create(['name'=>$d['firstName'].' '.$d['lastName'],'first_name'=>$d['firstName'],'last_name'=>$d['lastName'],'email'=>$d['email'],'password'=>$d['password']]);return response()->json(['token'=>$this->token($u),'user'=>$this->user($u)],201);}
 public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required']);$u=User::where('email',$d['email'])->first();if(!$u||!Hash::check($d['password'],$u->password))return response()->json(['error'=>'Invalid credentials'],401);return ['token'=>$this->token($u),'user'=>$this->user($u)];}
 public function forgot(Request $r){$r->validate(['email'=>'required|email']);return ['message'=>'If that email exists, a reset link has been sent.'];}
 public function reset(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required|min:8']);$u=User::where('email',$d['email'])->first();if($u){$u->update(['password'=>$d['password']]);}return ['message'=>'Password reset successfully.'];}
 public function me(Request $r){return $this->user($r->user());}
 public function products(Request $r){$q=Product::with('category');if($r->search)$q->where(fn($x)=>$x->where('name','like','%'.$r->search.'%')->orWhere('description','like','%'.$r->search.'%'));if($r->category)$q->whereHas('category',fn($x)=>$x->where('slug',$r->category));if($r->minPrice!==null)$q->where('price','>=',$r->minPrice);if($r->maxPrice!==null)$q->where('price','<=',$r->maxPrice);$sort=$r->sort;if($sort==='price-asc')$q->orderBy('price');elseif($sort==='price-desc')$q->orderByDesc('price');else $q->latest();$limit=min(100,max(1,(int)$r->input('limit',12)));$p=$q->paginate($limit);return ['items'=>collect($p->items())->map->toFrontend(),'total'=>$p->total(),'page'=>$p->currentPage(),'limit'=>$limit,'pages'=>$p->lastPage()];}
 public function product($id){$p=Product::with('category')->where('id',$id)->orWhere('slug',$id)->firstOrFail();return $p->toFrontend();}
 public function cartGet(Request $r){$c=$this->cart($r)->load('items.product');return ['items'=>$c->items->map(fn($i)=>['product'=>$i->product->toFrontend(),'quantity'=>$i->quantity])];}
 public function cartAdd(Request $r){$d=$r->validate(['productId'=>'required','quantity'=>'required|integer|min:1']);$c=$this->cart($r);$p=Product::findOrFail($d['productId']);$i=CartItem::updateOrCreate(['cart_id'=>$c->id,'product_id'=>$p->id],['quantity'=>$d['quantity']]);return $this->cartGet($r);}
 public function cartUpdate(Request $r,$id){$d=$r->validate(['quantity'=>'required|integer|min:1']);$this->cart($r)->items()->where('product_id',$id)->update($d);return $this->cartGet($r);}
 public function cartRemove(Request $r,$id){$this->cart($r)->items()->where('product_id',$id)->delete();return $this->cartGet($r);}
 public function checkout(Request $r){$d=$r->validate(['paymentToken'=>'nullable|string','deliveryMethod'=>'nullable|string','shippingAddress'=>'nullable|array']);$c=$this->cart($r)->load('items.product');if($c->items->isEmpty())return response()->json(['error'=>'Cart is empty'],422);$o=DB::transaction(function()use($c,$d,$r){$total=0;$items=[];foreach($c->items as $i){$p=Product::lockForUpdate()->find($i->product_id);if(!$p||$p->stock<$i->quantity)abort(422,'Insufficient stock for '.$i->product->name);$p->decrement('stock',$i->quantity);$total+=$p->price*$i->quantity;$items[]=['product_id'=>$p->id,'product_name'=>$p->name,'quantity'=>$i->quantity,'unit_price'=>$p->price];}$o=Order::create(['user_id'=>$r->user()?->id,'guest_token'=>$r->header('x-guest-token'),'status'=>'processing','total'=>$total,'shipping_address'=>$d['shippingAddress']??null,'delivery_method'=>$d['deliveryMethod']??null,'payment_reference'=>$d['paymentToken']?hash('sha256',$d['paymentToken']):null]);$o->items()->createMany($items);$c->items()->delete();return $o;});return response()->json($this->order($o->load('items','user')),201);}
 private function order($o){return ['id'=>(string)$o->id,'createdAt'=>$o->created_at,'status'=>$o->status,'total'=>$o->total,'items'=>$o->items->map(fn($i)=>['productName'=>$i->product_name,'quantity'=>$i->quantity,'unitPrice'=>$i->unit_price]),'user'=>$o->user?['email'=>$o->user->email,'firstName'=>$o->user->first_name,'lastName'=>$o->user->last_name]:null];}
 public function orders(Request $r){$q=Order::with('items','user');$u=$r->user();$q=$u?$q->where('user_id',$u->id):$q->where('guest_token',$r->header('x-guest-token'));return $q->latest()->get()->map(fn($o)=>$this->order($o));}
 public function wishlist(Request $r){return Wishlist::with('product')->where('user_id',$r->user()->id)->get()->map(fn($w)=>['product'=>$w->product->toFrontend()]);}
 public function wishlistAdd(Request $r,$id){Wishlist::firstOrCreate(['user_id'=>$r->user()->id,'product_id'=>$id]);return $this->wishlist($r);}
 public function wishlistRemove(Request $r,$id){Wishlist::where(['user_id'=>$r->user()->id,'product_id'=>$id])->delete();return $this->wishlist($r);}
 public function account(Request $r){return $this->user($r->user());}
 public function accountUpdate(Request $r){$d=$r->validate(['firstName'=>'sometimes|string','lastName'=>'sometimes|string','email'=>'sometimes|email','phone'=>'nullable|string']);$u=$r->user();$u->update(array_filter(['first_name'=>$d['firstName']??null,'last_name'=>$d['lastName']??null,'email'=>$d['email']??null,'phone'=>$d['phone']??null],fn($v)=>$v!==null));return $this->user($u->fresh());}
 public function password(Request $r){$d=$r->validate(['currentPassword'=>'required','newPassword'=>'required|min:8']);if(!Hash::check($d['currentPassword'],$r->user()->password))return response()->json(['error'=>'Current password is incorrect'],422);$r->user()->update(['password'=>$d['newPassword']]);return ['message'=>'Password updated'];}
 public function addressAdd(Request $r){$d=$r->validate(['line1'=>'required','city'=>'required','state'=>'required','postalCode'=>'required','country'=>'required']);$d['user_id']=$r->user()->id;$d['postal_code']=$d['postalCode'];unset($d['postalCode']);return Address::create($d);}
 public function addressUpdate(Request $r,$id){$a=$r->user()->addresses()->findOrFail($id);$d=$r->all();if(isset($d['postalCode'])){$d['postal_code']=$d['postalCode'];unset($d['postalCode']);} $a->update($d);return $a;}
 public function addressRemove(Request $r,$id){$r->user()->addresses()->whereKey($id)->delete();return response()->noContent();}
 public function newsletter(Request $r){$d=$r->validate(['email'=>'required|email']);DB::table('newsletters')->updateOrInsert(['email'=>$d['email']],['updated_at'=>now(),'created_at'=>now()]);return ['message'=>'Subscribed'];}
 public function reviews($id){return Review::where('product_id',$id)->latest()->get();}
 public function reviewAdd(Request $r,$id){$d=$r->validate(['rating'=>'required|integer|min:1|max:5','title'=>'nullable|string','body'=>'nullable|string']);$d['product_id']=$id;$d['user_id']=$r->user()->id;return Review::create($d);}
 public function adminDashboard(){return ['products'=>Product::count(),'orders'=>Order::count(),'revenue'=>Order::sum('total'),'lowStock'=>Product::where('stock','<',5)->count()];}
 public function adminProducts(){return Product::with('category')->latest()->get()->map->toFrontend();}
 public function adminProductCreate(Request $r){$d=$r->validate(['name'=>'required','price'=>'required|numeric','categoryId'=>'nullable','stock'=>'nullable|integer']);$d['slug']=Str::slug($d['name']).'-'.Str::lower(Str::random(5));$d['category_id']=$d['categoryId']??null;unset($d['categoryId']);return Product::create($d)->load('category')->toFrontend();}
 public function adminProductUpdate(Request $r,$id){$p=Product::findOrFail($id);$p->update($r->all());return $p->fresh()->load('category')->toFrontend();}
 public function adminProductDelete($id){Product::findOrFail($id)->delete();return response()->noContent();}
 public function adminOrders(){return Order::with('items','user')->latest()->get()->map(fn($o)=>$this->order($o));}
 public function adminOrderUpdate(Request $r,$id){$o=Order::findOrFail($id);$o->update($r->validate(['status'=>'required|string']));return $this->order($o->load('items','user'));}
 public function adminCategories(){return Category::withCount('products')->get()->map(fn($c)=>['id'=>(string)$c->id,'name'=>$c->name,'slug'=>$c->slug,'_count'=>['products'=>$c->products_count]]);}
 public function adminCategoryCreate(Request $r){return Category::create($r->validate(['name'=>'required','slug'=>'required|unique:categories','imageUrl'=>'nullable'])->only(['name','slug']));}
}
